name: 'PR to Develop: Unit Tests'
on:
  workflow_dispatch:

  push:
    branches: ["feature/**"]

  pull_request:
    branches: ["develop"]

env:
  WIP: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
  SA: ${{ secrets.GCP_SA }}

jobs:
  setup_and_upload_to_gcs:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Authenticate to google Ccoud
      - id: "auth"
        name: Authenticate to GCP
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ env.WIP }}
          service_account: ${{ env.SA }}

      # 3. Setup gcloud for project
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
      
      # 4. Upload files to cloud storage bukcet
      - name: Upload Unit Test Files to Cloud Storage
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: source/dataProcessingCode/src/tests
          destination: pyspark-testing-adev-spark
          process_gcloudignore: false
      
      # 5. Upload batch jobs to the cloud storage bucket
      - name: Upload Batch Jobs to Cloud storage
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: source/dataProcessingCode/src/main/jobs/batch_jobs
          destination: pyspark-jobs-adev-spark
          process_gcloudignore: false
          
